['COPAY_PCT', 'CWF_AMT_DAY', 'INVOICE_CNT', 'POLICY_CNT', 'ORG_PRES_AMT_VALUE', 'APP_AMT', 'REJECTED_AMT', 'SUB_AMT', 'CL_SOCIAL_PAY_AMT', 'CL_THIRD_PARTY_PAY_AMT', 'CL_OWNER_PAY_AMT', 'CL_SELF_CAT_PAY_AMT',

'FRAUD',
 
'M117', 'R600', 'R860', 'T450', 'R040', 'W100', 'M107', 'W420', 'W040', 'R270', 'R897', 'P1', 'P2', 'W360', 'M028', 'W080', 'R625', 'P15', 'P19', 'R560', 'R896', 'M149', 'W250', 'W450', 'W220', 'R140', 'R180', 'W020', 'R680', 'DT', 'P4', 'P8', 'W310', 'R130', 'M133', 'M060', 'W090', 'W260', 'R682', 'LB', 'R060', 'P5', 'W270', 'W070', 'W055', 'R030', 'P12', 'W380', 'P10', 'M143', 'R605', 'M029', 'R100', 'R542', 'W340', 'R260', 'P11', 'P3', 'R899', 'W280', 'W056', 'W105', 'M116', 'R894', 'W620', 'M114', 'M130', 'R170', 'P17', 'M144', 'DO', 'P20', 'M120', 'W180', 'T420', 'M110', 'M109', 'R658', 'M155', 'R540', 'W010', 'M101', 'R010', 'IB', 'DX', 'W230', 'R898', 'P9', 'R610', 'W410', 'T460', 'W050', 'BD', 'M002', 'W600', 'W290', 'W057', 'R520', 'M121', 'CF', 'T250', 'W400', 'W560', 'M004', 'W190', 'M111', 'P18', 'P16', 'T180', 'M118', 'W120', 'W210', 'LG', 'M009', 'W390', 'M113', 'W200', 'M119', 'W590', 'T190', 'M123', 'R530',

'BEN_TYPE_DB-IP', 'BEN_TYPE_DB-OP', 'BEN_TYPE_DT', 'BEN_TYPE_GG-IP', 'BEN_TYPE_GG-OP', 'BEN_TYPE_IP', 'BEN_TYPE_IPCASB', 'BEN_TYPE_JW-OP', 'BEN_TYPE_MA', 'BEN_TYPE_MAIP', 'BEN_TYPE_MAOP', 'BEN_TYPE_MDB', 'BEN_TYPE_MEMR', 'BEN_TYPE_MT', 'BEN_TYPE_OP', 'BEN_TYPE_PA', 'BEN_TYPE_VS', 'BEN_TYPE_YW-IP', 'BEN_TYPE_YW-OP',

'MBR_TYPE_Applicant', 'MBR_TYPE_Child', 'MBR_TYPE_Parents', 'MBR_TYPE_Spouse',

'BEN_HEAD_100PF', 'BEN_HEAD_100PF-JCF', 'BEN_HEAD_100PF-YPF', 'BEN_HEAD_ACUP', 'BEN_HEAD_BTAT', 'BEN_HEAD_CASB', 'BEN_HEAD_CASB-ZJ', 'BEN_HEAD_CC-CLF', 'BEN_HEAD_CC-GHF', 'BEN_HEAD_CC-JCF', 'BEN_HEAD_CC-MZSS', 'BEN_HEAD_CC-YPF', 'BEN_HEAD_CC-ZLF', 'BEN_HEAD_CR', 'BEN_HEAD_CWF', 'BEN_HEAD_CYDY', 'BEN_HEAD_ER', 'BEN_HEAD_EXC', 'BEN_HEAD_EXLS', 'BEN_HEAD_EXZL', 'BEN_HEAD_F-CJF', 'BEN_HEAD_F-CLF', 'BEN_HEAD_F-CWF', 'BEN_HEAD_F-GHF', 'BEN_HEAD_F-HERB', 'BEN_HEAD_F-JCF', 'BEN_HEAD_F-MZSS', 'BEN_HEAD_F-PHYS', 'BEN_HEAD_F-YPF', 'BEN_HEAD_F-ZFJC', 'BEN_HEAD_F-ZFYP', 'BEN_HEAD_F-ZLF', 'BEN_HEAD_F-ZYF', 'BEN_HEAD_F-ZYJC', 'BEN_HEAD_FLZFYP', 'BEN_HEAD_GHF', 'BEN_HEAD_HERB', 'BEN_HEAD_HVIS', 'BEN_HEAD_INFB', 'BEN_HEAD_JCF', 'BEN_HEAD_JSB-YPF', 'BEN_HEAD_JSB-ZLF', 'BEN_HEAD_JW-GHF', 'BEN_HEAD_JW-YPF', 'BEN_HEAD_JZF-JCF', 'BEN_HEAD_JZF-YPF', 'BEN_HEAD_JZF-ZFYP', 'BEN_HEAD_JZS-GHF', 'BEN_HEAD_JZS-JCF', 'BEN_HEAD_JZS-YPF', 'BEN_HEAD_LAB', 'BEN_HEAD_LAMB', 'BEN_HEAD_LC', 'BEN_HEAD_LENS', 'BEN_HEAD_MA/COP', 'BEN_HEAD_MA/NBC', 'BEN_HEAD_MF', 'BEN_HEAD_MISC', 'BEN_HEAD_MND', 'BEN_HEAD_MSD', 'BEN_HEAD_MT-CLF', 'BEN_HEAD_MT-GHF', 'BEN_HEAD_MT-JCF', 'BEN_HEAD_MT-MZSS', 'BEN_HEAD_MT-YPF', 'BEN_HEAD_MT-ZLF', 'BEN_HEAD_MTR', 'BEN_HEAD_MZGKYC', 'BEN_HEAD_MZY', 'BEN_HEAD_NBC', 'BEN_HEAD_NF', 'BEN_HEAD_NF-JCF', 'BEN_HEAD_NF-YPF', 'BEN_HEAD_NS-GHF', 'BEN_HEAD_NS-JCF', 'BEN_HEAD_NS-YPF', 'BEN_HEAD_NS-ZFYP', 'BEN_HEAD_NS-ZLF', 'BEN_HEAD_O1K-MZY', 'BEN_HEAD_O1K-ZFYP', 'BEN_HEAD_O1K-ZYF', 'BEN_HEAD_OPR', 'BEN_HEAD_OV', 'BEN_HEAD_PHYS', 'BEN_HEAD_PS', 'BEN_HEAD_RB', 'BEN_HEAD_RH-CLF', 'BEN_HEAD_RH-GHF', 'BEN_HEAD_RH-JCF', 'BEN_HEAD_RH-OV', 'BEN_HEAD_RH-PS', 'BEN_HEAD_RH-YPF', 'BEN_HEAD_RH-ZLF', 'BEN_HEAD_RX', 'BEN_HEAD_S-CJF', 'BEN_HEAD_S-CLF', 'BEN_HEAD_S-CWF', 'BEN_HEAD_S-FMF', 'BEN_HEAD_S-GHF', 'BEN_HEAD_S-JCF', 'BEN_HEAD_S-MT', 'BEN_HEAD_S-MZSS', 'BEN_HEAD_S-OV', 'BEN_HEAD_S-PS', 'BEN_HEAD_S-YPF', 'BEN_HEAD_S-ZFYP', 'BEN_HEAD_S-ZLF', 'BEN_HEAD_S-ZYF', 'BEN_HEAD_S-ZYJC', 'BEN_HEAD_SC1', 'BEN_HEAD_SH1', 'BEN_HEAD_SPFRM', 'BEN_HEAD_SPLEN', 'BEN_HEAD_THER', 'BEN_HEAD_TRTC', 'BEN_HEAD_TX-GHF', 'BEN_HEAD_TX-JCF', 'BEN_HEAD_TX-MZSS', 'BEN_HEAD_TX-YPF', 'BEN_HEAD_TX-ZLF', 'BEN_HEAD_WSS-YPF', 'BEN_HEAD_YJ-GHF', 'BEN_HEAD_YJ-JCF', 'BEN_HEAD_YJ-MZSS', 'BEN_HEAD_YJ-YPF', 'BEN_HEAD_YJ-ZLF', 'BEN_HEAD_YPF', 'BEN_HEAD_YW-JCF', 'BEN_HEAD_YW-YPF', 'BEN_HEAD_YW-ZLF', 'BEN_HEAD_YWS-ZYF', 'BEN_HEAD_ZLF', 'BEN_HEAD_ZY-CWF', 'BEN_HEAD_ZY-CYDY', 'BEN_HEAD_ZY-LC', 'BEN_HEAD_ZY-YPF', 'BEN_HEAD_ZY-ZFYP', 'BEN_HEAD_ZYF',

'PROV_LEVEL_一级', 'PROV_LEVEL_三级', 'PROV_LEVEL_二级', 'PROV_LEVEL_医保', 'PROV_LEVEL_卫生所', 'PROV_LEVEL_未知', 'PROV_LEVEL_未评级', 'PROV_LEVEL_特需', 'PROV_LEVEL_非医保']

In [1]:
import tensorflow as tf
import keras
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split,KFold
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
import time
import pandas
import seaborn as sns

In [2]:
import bisect

In [3]:
plt.rcParams['font.sans-serif'] = ['Simhei']   #用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] =  False    #用来正常显示负号

import os
import time
pd.set_option('display.max_columns', 999)    #设置数据展示的最大列数和最大行数
pd.set_option('display.max_rows', 500)

In [6]:
filename='test'

df=pandas.read_excel(filename+'.xlsx')

In [7]:
#根据CL_LINE_STATUS列创建FRAUD列
df.insert(df.shape[1],"FRAUD",0)
for i in df.index:
    if df.loc[i,"CL_LINE_STATUS"]=="AC":
        df.loc[i,"FRAUD"]=0
    else:
        df.loc[i,"FRAUD"]=1

In [8]:
df["FRAUD"].dtype

dtype('int64')

In [9]:
df['PROV_LEVEL'].fillna('未知',inplace=True)

C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3710005681.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PROV_LEVEL'].fillna('未知',inplace=True)

In [10]:
value_list=[
    'COPAY_PCT',
    'CWF_AMT_DAY',
    'INVOICE_CNT',
    'POLICY_CNT',
    'ORG_PRES_AMT_VALUE',
    'APP_AMT',
    'REJECTED_AMT',
    'SUB_AMT',
    'CL_SOCIAL_PAY_AMT',
    'CL_THIRD_PARTY_PAY_AMT',
    'CL_OWNER_PAY_AMT',
    'CL_SELF_CAT_PAY_AMT',
    'FRAUD',]

In [11]:
string_list=[
    'CODES',
    'BEN_TYPE',
    'MBR_TYPE',
    'BEN_HEAD',
    'PROV_LEVEL',]

In [12]:
df=df[string_list+value_list]

In [13]:
code_list=['M117', 'R600', 'R860', 'T450', 'R040', 'W100', 'M107', 'W420', 'W040', 'R270', 'R897', 'P1', 'P2', 'W360', 'M028', 'W080', 'R625', 'P15', 'P19', 'R560', 'R896', 'M149', 'W250', 'W450', 'W220', 'R140', 'R180', 'W020', 'R680', 'DT', 'P4', 'P8', 'W310', 'R130', 'M133', 'M060', 'W090', 'W260', 'R682', 'LB', 'R060', 'P5', 'W270', 'W070', 'W055', 'R030', 'P12', 'W380', 'P10', 'M143', 'R605', 'M029', 'R100', 'R542', 'W340', 'R260', 'P11', 'P3', 'R899', 'W280', 'W056', 'W105', 'M116', 'R894', 'W620', 'M114', 'M130', 'R170', 'P17', 'M144', 'DO', 'P20', 'M120', 'W180', 'T420', 'M110', 'M109', 'R658', 'M155', 'R540', 'W010', 'M101', 'R010', 'IB', 'DX', 'W230', 'R898', 'P9', 'R610', 'W410', 'T460', 'W050', 'BD', 'M002', 'W600', 'W290', 'W057', 'R520', 'M121', 'CF', 'T250', 'W400', 'W560', 'M004', 'W190', 'M111', 'P18', 'P16', 'T180', 'M118', 'W120', 'W210', 'LG', 'M009', 'W390', 'M113', 'W200', 'M119', 'W590', 'T190', 'M123', 'R530',]

# 对于每个code，在df里插入列并赋值
for code in code_list:
    if code not in df.columns: 
        df.insert(df.shape[1],code,0)
    for i in df.index:
        codes=df['CODES'][i]
        codes=str(codes)
        if code in codes:
            df.loc[i,code]=1

C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\372437418.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)

In [14]:
df.drop(columns=['CODES'],inplace=True)

In [15]:
AMT_columns = [
    'ORG_PRES_AMT_VALUE',
    'APP_AMT',
    'REJECTED_AMT',
    'SUB_AMT',
    'CL_SOCIAL_PAY_AMT',
    'CL_THIRD_PARTY_PAY_AMT',
    'CL_OWNER_PAY_AMT',
    'CL_SELF_CAT_PAY_AMT'
]

In [16]:
def log_cal(x):
    x=abs(x)
    x+=0.001
    return np.log10(x)

In [17]:
for i in AMT_columns:
    df[i]=df[i].apply(log_cal)

In [18]:
BEN_TYPE_list=['BEN_TYPE_DB-IP', 'BEN_TYPE_DB-OP', 'BEN_TYPE_DT', 'BEN_TYPE_GG-IP', 'BEN_TYPE_GG-OP', 'BEN_TYPE_IP', 'BEN_TYPE_IPCASB', 'BEN_TYPE_JW-OP', 'BEN_TYPE_MA', 'BEN_TYPE_MAIP', 'BEN_TYPE_MAOP', 'BEN_TYPE_MDB', 'BEN_TYPE_MEMR', 'BEN_TYPE_MT', 'BEN_TYPE_OP', 'BEN_TYPE_PA', 'BEN_TYPE_VS', 'BEN_TYPE_YW-IP', 'BEN_TYPE_YW-OP',]

In [19]:
MBR_TYPE_list=['MBR_TYPE_Applicant', 'MBR_TYPE_Child', 'MBR_TYPE_Parents', 'MBR_TYPE_Spouse',


]

BEN_HEAD_list=[
'BEN_HEAD_100PF', 'BEN_HEAD_100PF-JCF', 'BEN_HEAD_100PF-YPF', 'BEN_HEAD_ACUP', 'BEN_HEAD_BTAT', 'BEN_HEAD_CASB', 'BEN_HEAD_CASB-ZJ', 'BEN_HEAD_CC-CLF', 'BEN_HEAD_CC-GHF', 'BEN_HEAD_CC-JCF', 'BEN_HEAD_CC-MZSS', 'BEN_HEAD_CC-YPF', 'BEN_HEAD_CC-ZLF', 'BEN_HEAD_CR', 'BEN_HEAD_CWF', 'BEN_HEAD_CYDY', 'BEN_HEAD_ER', 'BEN_HEAD_EXC', 'BEN_HEAD_EXLS', 'BEN_HEAD_EXZL', 'BEN_HEAD_F-CJF', 'BEN_HEAD_F-CLF', 'BEN_HEAD_F-CWF', 'BEN_HEAD_F-GHF', 'BEN_HEAD_F-HERB', 'BEN_HEAD_F-JCF', 'BEN_HEAD_F-MZSS', 'BEN_HEAD_F-PHYS', 'BEN_HEAD_F-YPF', 'BEN_HEAD_F-ZFJC', 'BEN_HEAD_F-ZFYP', 'BEN_HEAD_F-ZLF', 'BEN_HEAD_F-ZYF', 'BEN_HEAD_F-ZYJC', 'BEN_HEAD_FLZFYP', 'BEN_HEAD_GHF', 'BEN_HEAD_HERB', 'BEN_HEAD_HVIS', 'BEN_HEAD_INFB', 'BEN_HEAD_JCF', 'BEN_HEAD_JSB-YPF', 'BEN_HEAD_JSB-ZLF', 'BEN_HEAD_JW-GHF', 'BEN_HEAD_JW-YPF', 'BEN_HEAD_JZF-JCF', 'BEN_HEAD_JZF-YPF', 'BEN_HEAD_JZF-ZFYP', 'BEN_HEAD_JZS-GHF', 'BEN_HEAD_JZS-JCF', 'BEN_HEAD_JZS-YPF', 'BEN_HEAD_LAB', 'BEN_HEAD_LAMB', 'BEN_HEAD_LC', 'BEN_HEAD_LENS', 'BEN_HEAD_MA/COP', 'BEN_HEAD_MA/NBC', 'BEN_HEAD_MF', 'BEN_HEAD_MISC', 'BEN_HEAD_MND', 'BEN_HEAD_MSD', 'BEN_HEAD_MT-CLF', 'BEN_HEAD_MT-GHF', 'BEN_HEAD_MT-JCF', 'BEN_HEAD_MT-MZSS', 'BEN_HEAD_MT-YPF', 'BEN_HEAD_MT-ZLF', 'BEN_HEAD_MTR', 'BEN_HEAD_MZGKYC', 'BEN_HEAD_MZY', 'BEN_HEAD_NBC', 'BEN_HEAD_NF', 'BEN_HEAD_NF-JCF', 'BEN_HEAD_NF-YPF', 'BEN_HEAD_NS-GHF', 'BEN_HEAD_NS-JCF', 'BEN_HEAD_NS-YPF', 'BEN_HEAD_NS-ZFYP', 'BEN_HEAD_NS-ZLF', 'BEN_HEAD_O1K-MZY', 'BEN_HEAD_O1K-ZFYP', 'BEN_HEAD_O1K-ZYF', 'BEN_HEAD_OPR', 'BEN_HEAD_OV', 'BEN_HEAD_PHYS', 'BEN_HEAD_PS', 'BEN_HEAD_RB', 'BEN_HEAD_RH-CLF', 'BEN_HEAD_RH-GHF', 'BEN_HEAD_RH-JCF', 'BEN_HEAD_RH-OV', 'BEN_HEAD_RH-PS', 'BEN_HEAD_RH-YPF', 'BEN_HEAD_RH-ZLF', 'BEN_HEAD_RX', 'BEN_HEAD_S-CJF', 'BEN_HEAD_S-CLF', 'BEN_HEAD_S-CWF', 'BEN_HEAD_S-FMF', 'BEN_HEAD_S-GHF', 'BEN_HEAD_S-JCF', 'BEN_HEAD_S-MT', 'BEN_HEAD_S-MZSS', 'BEN_HEAD_S-OV', 'BEN_HEAD_S-PS', 'BEN_HEAD_S-YPF', 'BEN_HEAD_S-ZFYP', 'BEN_HEAD_S-ZLF', 'BEN_HEAD_S-ZYF', 'BEN_HEAD_S-ZYJC', 'BEN_HEAD_SC1', 'BEN_HEAD_SH1', 'BEN_HEAD_SPFRM', 'BEN_HEAD_SPLEN', 'BEN_HEAD_THER', 'BEN_HEAD_TRTC', 'BEN_HEAD_TX-GHF', 'BEN_HEAD_TX-JCF', 'BEN_HEAD_TX-MZSS', 'BEN_HEAD_TX-YPF', 'BEN_HEAD_TX-ZLF', 'BEN_HEAD_WSS-YPF', 'BEN_HEAD_YJ-GHF', 'BEN_HEAD_YJ-JCF', 'BEN_HEAD_YJ-MZSS', 'BEN_HEAD_YJ-YPF', 'BEN_HEAD_YJ-ZLF', 'BEN_HEAD_YPF', 'BEN_HEAD_YW-JCF', 'BEN_HEAD_YW-YPF', 'BEN_HEAD_YW-ZLF', 'BEN_HEAD_YWS-ZYF', 'BEN_HEAD_ZLF', 'BEN_HEAD_ZY-CWF', 'BEN_HEAD_ZY-CYDY', 'BEN_HEAD_ZY-LC', 'BEN_HEAD_ZY-YPF', 'BEN_HEAD_ZY-ZFYP', 'BEN_HEAD_ZYF',
]

PROV_LEVEL_list=[
'PROV_LEVEL_一级', 'PROV_LEVEL_三级', 'PROV_LEVEL_二级', 'PROV_LEVEL_医保', 'PROV_LEVEL_卫生所', 'PROV_LEVEL_未知', 'PROV_LEVEL_未评级', 'PROV_LEVEL_特需', 'PROV_LEVEL_非医保']

In [20]:
def dummies_column(column_name,column_list):
    for code in column_list:
        if code not in df.columns: 
            df.insert(df.shape[1],code,0)
        for i in df.index:
            codes=df[column_name][i]
            codes=str(codes)
            if code[len(column_name)+1:] in codes:
                df.loc[i,code]=1

def drop_columns(column_name):
    df.drop(columns=[column_name],inplace=True)

In [21]:
dummies_column('BEN_TYPE',BEN_TYPE_list)
drop_columns('BEN_TYPE')

C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)

In [22]:
dummies_column('MBR_TYPE',MBR_TYPE_list)
drop_columns('MBR_TYPE')
dummies_column('BEN_HEAD',BEN_HEAD_list)
drop_columns('BEN_HEAD')
dummies_column('PROV_LEVEL',PROV_LEVEL_list)
drop_columns('PROV_LEVEL')

C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)
C:\Users\12132\AppData\Local\Temp\ipykernel_11728\3018008026.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(df.shape[1],code,0)

In [23]:
df.tail()

,COPAY_PCT,CWF_AMT_DAY,INVOICE_CNT,POLICY_CNT,ORG_PRES_AMT_VALUE,APP_AMT,REJECTED_AMT,SUB_AMT,CL_SOCIAL_PAY_AMT,CL_THIRD_PARTY_PAY_AMT,CL_OWNER_PAY_AMT,CL_SELF_CAT_PAY_AMT,FRAUD,M117,R600,R860,T450,R040,W100,M107,W420,W040,R270,R897,P1,P2,W360,M028,W080,R625,P15,P19,R560,R896,M149,W250,W450,W220,R140,R180,W020,R680,DT,P4,P8,W310,R130,M133,M060,W090,W260,R682,LB,R060,P5,W270,W070,W055,R030,P12,W380,P10,M143,R605,M029,R100,R542,W340,R260,P11,P3,R899,W280,W056,W105,M116,R894,W620,M114,M130,R170,P17,M144,DO,P20,M120,W180,T420,M110,M109,R658,M155,R540,W010,M101,R010,IB,DX,W230,R898,P9,R610,W410,T460,W050,BD,M002,W600,W290,W057,R520,M121,CF,T250,W400,W560,M004,W190,M111,P18,P16,T180,M118,W120,W210,LG,M009,W390,M113,W200,M119,W590,T190,M123,R530,BEN_TYPE_DB-IP,BEN_TYPE_DB-OP,BEN_TYPE_DT,BEN_TYPE_GG-IP,BEN_TYPE_GG-OP,BEN_TYPE_IP,BEN_TYPE_IPCASB,BEN_TYPE_JW-OP,BEN_TYPE_MA,BEN_TYPE_MAIP,BEN_TYPE_MAOP,BEN_TYPE_MDB,BEN_TYPE_MEMR,BEN_TYPE_MT,BEN_TYPE_OP,BEN_TYPE_PA,BEN_TYPE_VS,BEN_TYPE_YW-IP,BEN_TYPE_YW-OP,MBR_TYPE_Applicant,MBR_TYPE_Child,MBR_TYPE_Parents,MBR_TYPE_Spouse,BEN_HEAD_100PF,BEN_HEAD_100PF-JCF,BEN_HEAD_100PF-YPF,BEN_HEAD_ACUP,BEN_HEAD_BTAT,BEN_HEAD_CASB,BEN_HEAD_CASB-ZJ,BEN_HEAD_CC-CLF,BEN_HEAD_CC-GHF,BEN_HEAD_CC-JCF,BEN_HEAD_CC-MZSS,BEN_HEAD_CC-YPF,BEN_HEAD_CC-ZLF,BEN_HEAD_CR,BEN_HEAD_CWF,BEN_HEAD_CYDY,BEN_HEAD_ER,BEN_HEAD_EXC,BEN_HEAD_EXLS,BEN_HEAD_EXZL,BEN_HEAD_F-CJF,BEN_HEAD_F-CLF,BEN_HEAD_F-CWF,BEN_HEAD_F-GHF,BEN_HEAD_F-HERB,BEN_HEAD_F-JCF,BEN_HEAD_F-MZSS,BEN_HEAD_F-PHYS,BEN_HEAD_F-YPF,BEN_HEAD_F-ZFJC,BEN_HEAD_F-ZFYP,BEN_HEAD_F-ZLF,BEN_HEAD_F-ZYF,BEN_HEAD_F-ZYJC,BEN_HEAD_FLZFYP,BEN_HEAD_GHF,BEN_HEAD_HERB,BEN_HEAD_HVIS,BEN_HEAD_INFB,BEN_HEAD_JCF,BEN_HEAD_JSB-YPF,BEN_HEAD_JSB-ZLF,BEN_HEAD_JW-GHF,BEN_HEAD_JW-YPF,BEN_HEAD_JZF-JCF,BEN_HEAD_JZF-YPF,BEN_HEAD_JZF-ZFYP,BEN_HEAD_JZS-GHF,BEN_HEAD_JZS-JCF,BEN_HEAD_JZS-YPF,BEN_HEAD_LAB,BEN_HEAD_LAMB,BEN_HEAD_LC,BEN_HEAD_LENS,BEN_HEAD_MA/COP,BEN_HEAD_MA/NBC,BEN_HEAD_MF,BEN_HEAD_MISC,BEN_HEAD_MND,BEN_HEAD_MSD,BEN_HEAD_MT-CLF,BEN_HEAD_MT-GHF,BEN_HEAD_MT-JCF,BEN_HEAD_MT-MZSS,BEN_HEAD_MT-YPF,BEN_HEAD_MT-ZLF,BEN_HEAD_MTR,BEN_HEAD_MZGKYC,BEN_HEAD_MZY,BEN_HEAD_NBC,BEN_HEAD_NF,BEN_HEAD_NF-JCF,BEN_HEAD_NF-YPF,BEN_HEAD_NS-GHF,BEN_HEAD_NS-JCF,BEN_HEAD_NS-YPF,BEN_HEAD_NS-ZFYP,BEN_HEAD_NS-ZLF,BEN_HEAD_O1K-MZY,BEN_HEAD_O1K-ZFYP,BEN_HEAD_O1K-ZYF,BEN_HEAD_OPR,BEN_HEAD_OV,BEN_HEAD_PHYS,BEN_HEAD_PS,BEN_HEAD_RB,BEN_HEAD_RH-CLF,BEN_HEAD_RH-GHF,BEN_HEAD_RH-JCF,BEN_HEAD_RH-OV,BEN_HEAD_RH-PS,BEN_HEAD_RH-YPF,BEN_HEAD_RH-ZLF,BEN_HEAD_RX,BEN_HEAD_S-CJF,BEN_HEAD_S-CLF,BEN_HEAD_S-CWF,BEN_HEAD_S-FMF,BEN_HEAD_S-GHF,BEN_HEAD_S-JCF,BEN_HEAD_S-MT,BEN_HEAD_S-MZSS,BEN_HEAD_S-OV,BEN_HEAD_S-PS,BEN_HEAD_S-YPF,BEN_HEAD_S-ZFYP,BEN_HEAD_S-ZLF,BEN_HEAD_S-ZYF,BEN_HEAD_S-ZYJC,BEN_HEAD_SC1,BEN_HEAD_SH1,BEN_HEAD_SPFRM,BEN_HEAD_SPLEN,BEN_HEAD_THER,BEN_HEAD_TRTC,BEN_HEAD_TX-GHF,BEN_HEAD_TX-JCF,BEN_HEAD_TX-MZSS,BEN_HEAD_TX-YPF,BEN_HEAD_TX-ZLF,BEN_HEAD_WSS-YPF,BEN_HEAD_YJ-GHF,BEN_HEAD_YJ-JCF,BEN_HEAD_YJ-MZSS,BEN_HEAD_YJ-YPF,BEN_HEAD_YJ-ZLF,BEN_HEAD_YPF,BEN_HEAD_YW-JCF,BEN_HEAD_YW-YPF,BEN_HEAD_YW-ZLF,BEN_HEAD_YWS-ZYF,BEN_HEAD_ZLF,BEN_HEAD_ZY-CWF,BEN_HEAD_ZY-CYDY,BEN_HEAD_ZY-LC,BEN_HEAD_ZY-YPF,BEN_HEAD_ZY-ZFYP,BEN_HEAD_ZYF,PROV_LEVEL_一级,PROV_LEVEL_三级,PROV_LEVEL_二级,PROV_LEVEL_医保,PROV_LEVEL_卫生所,PROV_LEVEL_未知,PROV_LEVEL_未评级,PROV_LEVEL_特需,PROV_LEVEL_非医保
996,45,0,2,1,1.553045,1.206313,1.293385,1.553045,-3.00000,-3.0,-3.000000,0.495683,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
997,55,0,1,1,0.578754,-3.000000,0.578754,0.578754,-3.00000,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
998,45,0,12,1,1.204147,0.342620,1.139911,1.342442,-3.00000,-3.0,0.778224,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
999,70,0,12,1,-0.536107,-0.696804,-1.040959,0.301247,0.23325,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1000,70,0,12,1,1.933492,1.778593,1.410625,2.757298,2.68670,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [24]:
def value_replace(column_name,divide_list):
    for i in df.index:
        value=df[column_name][i]+1
        new_value=bisect.bisect_left(divide_list,value)
        df.loc[i,column_name]=new_value

In [25]:
bisect.bisect_left([20, 30, 50, 55, 60, 65, 70, 72, 75, 80, 85, 90, 95, 100],31)

2

In [26]:
value_replace('COPAY_PCT',[20, 30, 45, 50, 55, 60, 65, 70, 72, 75, 80, 85, 90, 95, 100])
value_replace('CWF_AMT_DAY',[0, 25, 29, 30, 40, 50, 80, 100, 120, 150, 200, 300])

In [27]:
df.tail()

,COPAY_PCT,CWF_AMT_DAY,INVOICE_CNT,POLICY_CNT,ORG_PRES_AMT_VALUE,APP_AMT,REJECTED_AMT,SUB_AMT,CL_SOCIAL_PAY_AMT,CL_THIRD_PARTY_PAY_AMT,CL_OWNER_PAY_AMT,CL_SELF_CAT_PAY_AMT,FRAUD,M117,R600,R860,T450,R040,W100,M107,W420,W040,R270,R897,P1,P2,W360,M028,W080,R625,P15,P19,R560,R896,M149,W250,W450,W220,R140,R180,W020,R680,DT,P4,P8,W310,R130,M133,M060,W090,W260,R682,LB,R060,P5,W270,W070,W055,R030,P12,W380,P10,M143,R605,M029,R100,R542,W340,R260,P11,P3,R899,W280,W056,W105,M116,R894,W620,M114,M130,R170,P17,M144,DO,P20,M120,W180,T420,M110,M109,R658,M155,R540,W010,M101,R010,IB,DX,W230,R898,P9,R610,W410,T460,W050,BD,M002,W600,W290,W057,R520,M121,CF,T250,W400,W560,M004,W190,M111,P18,P16,T180,M118,W120,W210,LG,M009,W390,M113,W200,M119,W590,T190,M123,R530,BEN_TYPE_DB-IP,BEN_TYPE_DB-OP,BEN_TYPE_DT,BEN_TYPE_GG-IP,BEN_TYPE_GG-OP,BEN_TYPE_IP,BEN_TYPE_IPCASB,BEN_TYPE_JW-OP,BEN_TYPE_MA,BEN_TYPE_MAIP,BEN_TYPE_MAOP,BEN_TYPE_MDB,BEN_TYPE_MEMR,BEN_TYPE_MT,BEN_TYPE_OP,BEN_TYPE_PA,BEN_TYPE_VS,BEN_TYPE_YW-IP,BEN_TYPE_YW-OP,MBR_TYPE_Applicant,MBR_TYPE_Child,MBR_TYPE_Parents,MBR_TYPE_Spouse,BEN_HEAD_100PF,BEN_HEAD_100PF-JCF,BEN_HEAD_100PF-YPF,BEN_HEAD_ACUP,BEN_HEAD_BTAT,BEN_HEAD_CASB,BEN_HEAD_CASB-ZJ,BEN_HEAD_CC-CLF,BEN_HEAD_CC-GHF,BEN_HEAD_CC-JCF,BEN_HEAD_CC-MZSS,BEN_HEAD_CC-YPF,BEN_HEAD_CC-ZLF,BEN_HEAD_CR,BEN_HEAD_CWF,BEN_HEAD_CYDY,BEN_HEAD_ER,BEN_HEAD_EXC,BEN_HEAD_EXLS,BEN_HEAD_EXZL,BEN_HEAD_F-CJF,BEN_HEAD_F-CLF,BEN_HEAD_F-CWF,BEN_HEAD_F-GHF,BEN_HEAD_F-HERB,BEN_HEAD_F-JCF,BEN_HEAD_F-MZSS,BEN_HEAD_F-PHYS,BEN_HEAD_F-YPF,BEN_HEAD_F-ZFJC,BEN_HEAD_F-ZFYP,BEN_HEAD_F-ZLF,BEN_HEAD_F-ZYF,BEN_HEAD_F-ZYJC,BEN_HEAD_FLZFYP,BEN_HEAD_GHF,BEN_HEAD_HERB,BEN_HEAD_HVIS,BEN_HEAD_INFB,BEN_HEAD_JCF,BEN_HEAD_JSB-YPF,BEN_HEAD_JSB-ZLF,BEN_HEAD_JW-GHF,BEN_HEAD_JW-YPF,BEN_HEAD_JZF-JCF,BEN_HEAD_JZF-YPF,BEN_HEAD_JZF-ZFYP,BEN_HEAD_JZS-GHF,BEN_HEAD_JZS-JCF,BEN_HEAD_JZS-YPF,BEN_HEAD_LAB,BEN_HEAD_LAMB,BEN_HEAD_LC,BEN_HEAD_LENS,BEN_HEAD_MA/COP,BEN_HEAD_MA/NBC,BEN_HEAD_MF,BEN_HEAD_MISC,BEN_HEAD_MND,BEN_HEAD_MSD,BEN_HEAD_MT-CLF,BEN_HEAD_MT-GHF,BEN_HEAD_MT-JCF,BEN_HEAD_MT-MZSS,BEN_HEAD_MT-YPF,BEN_HEAD_MT-ZLF,BEN_HEAD_MTR,BEN_HEAD_MZGKYC,BEN_HEAD_MZY,BEN_HEAD_NBC,BEN_HEAD_NF,BEN_HEAD_NF-JCF,BEN_HEAD_NF-YPF,BEN_HEAD_NS-GHF,BEN_HEAD_NS-JCF,BEN_HEAD_NS-YPF,BEN_HEAD_NS-ZFYP,BEN_HEAD_NS-ZLF,BEN_HEAD_O1K-MZY,BEN_HEAD_O1K-ZFYP,BEN_HEAD_O1K-ZYF,BEN_HEAD_OPR,BEN_HEAD_OV,BEN_HEAD_PHYS,BEN_HEAD_PS,BEN_HEAD_RB,BEN_HEAD_RH-CLF,BEN_HEAD_RH-GHF,BEN_HEAD_RH-JCF,BEN_HEAD_RH-OV,BEN_HEAD_RH-PS,BEN_HEAD_RH-YPF,BEN_HEAD_RH-ZLF,BEN_HEAD_RX,BEN_HEAD_S-CJF,BEN_HEAD_S-CLF,BEN_HEAD_S-CWF,BEN_HEAD_S-FMF,BEN_HEAD_S-GHF,BEN_HEAD_S-JCF,BEN_HEAD_S-MT,BEN_HEAD_S-MZSS,BEN_HEAD_S-OV,BEN_HEAD_S-PS,BEN_HEAD_S-YPF,BEN_HEAD_S-ZFYP,BEN_HEAD_S-ZLF,BEN_HEAD_S-ZYF,BEN_HEAD_S-ZYJC,BEN_HEAD_SC1,BEN_HEAD_SH1,BEN_HEAD_SPFRM,BEN_HEAD_SPLEN,BEN_HEAD_THER,BEN_HEAD_TRTC,BEN_HEAD_TX-GHF,BEN_HEAD_TX-JCF,BEN_HEAD_TX-MZSS,BEN_HEAD_TX-YPF,BEN_HEAD_TX-ZLF,BEN_HEAD_WSS-YPF,BEN_HEAD_YJ-GHF,BEN_HEAD_YJ-JCF,BEN_HEAD_YJ-MZSS,BEN_HEAD_YJ-YPF,BEN_HEAD_YJ-ZLF,BEN_HEAD_YPF,BEN_HEAD_YW-JCF,BEN_HEAD_YW-YPF,BEN_HEAD_YW-ZLF,BEN_HEAD_YWS-ZYF,BEN_HEAD_ZLF,BEN_HEAD_ZY-CWF,BEN_HEAD_ZY-CYDY,BEN_HEAD_ZY-LC,BEN_HEAD_ZY-YPF,BEN_HEAD_ZY-ZFYP,BEN_HEAD_ZYF,PROV_LEVEL_一级,PROV_LEVEL_三级,PROV_LEVEL_二级,PROV_LEVEL_医保,PROV_LEVEL_卫生所,PROV_LEVEL_未知,PROV_LEVEL_未评级,PROV_LEVEL_特需,PROV_LEVEL_非医保
996,3,1,2,1,1.553045,1.206313,1.293385,1.553045,-3.00000,-3.0,-3.000000,0.495683,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
997,5,1,1,1,0.578754,-3.000000,0.578754,0.578754,-3.00000,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
998,3,1,12,1,1.204147,0.342620,1.139911,1.342442,-3.00000,-3.0,0.778224,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
999,8,1,12,1,-0.536107,-0.696804,-1.040959,0.301247,0.23325,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1000,8,1,12,1,1.933492,1.778593,1.410625,2.757298,2.68670,-3.0,-3.000000,-3.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [39]:
from keras.models import load_model
loaded_model=load_model('mlp_model_2.keras')

In [29]:
df.drop(columns=['APP_AMT', 'REJECTED_AMT'],inplace= True)

In [30]:
X = df.drop(columns=['FRAUD'])
y = df['FRAUD']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Columns: 302 entries, COPAY_PCT to PROV_LEVEL_非医保
dtypes: float64(6), int64(296)
memory usage: 2.3 MB

In [40]:
y_pred=loaded_model.predict(X)
y_pred=[y_pred>=0.5]
y_pred=y_pred[0].astype(int)
# 评估模型
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))
print("Classification Report:")
print(classification_report(y, y_pred,digits=6))

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[799   0]
 [ 26 176]]
Classification Report:
              precision    recall  f1-score   support

           0   0.968485  1.000000  0.983990       799
           1   1.000000  0.871287  0.931217       202

    accuracy                       0.974026      1001
   macro avg   0.984242  0.935644  0.957604      1001
weighted avg   0.974845  0.974026  0.973341      1001

In [36]:
# random forest
from sklearn.ensemble import RandomForestClassifier
import pickle
#导入model_rfc.pkl
with open('xgbc_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [37]:
y_pred=loaded_model.predict(X)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))
print("Classification Report:")
print(classification_report(y, y_pred,digits=6))

Confusion Matrix:
[[799   0]
 [ 16 186]]
Classification Report:
              precision    recall  f1-score   support

           0   0.980368  1.000000  0.990087       799
           1   1.000000  0.920792  0.958763       202

    accuracy                       0.984016      1001
   macro avg   0.990184  0.960396  0.974425      1001
weighted avg   0.984330  0.984016  0.983766      1001